env:
  browser: true
  es6: true
  node: true
  mocha: true

extends: 'eslint:recommended'

parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module

plugins:
  - react

rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - double
  semi:
    - warn
    - always
  no-unused-vars: 1
